services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  FSG\OidcAzure\:
    resource: '../Classes/*'

  FSG\OidcAzure\EventListener\AuthenticationGetUserGroupsEventListener:
    tags:
      - name: event.listener
        identifier: 'oidc-azure/authentication-get-user-groups-event-listener'
        event: Causal\Oidc\Event\AuthenticationGetUserGroupsEvent

  FSG\OidcAzure\EventListener\ModifyUserEventListener:
    tags:
      - name: event.listener
        identifier: 'oidc-azure/modify-user-event-listener'
        event: Causal\Oidc\Event\ModifyUserEvent
